services:
  - mongo:latest

stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
 
  script:
    - cd NotificationService
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  image: golang:latest
  script:
    - mkdir -p mybinaries
    - go build -o mybinaries ./...
  artifacts:
    paths:
      - mybinaries

