// Code generated by MockGen. DO NOT EDIT.
// Source: NotificationService/internal/route (interfaces: MessageSenderInterface)

// Package route is a generated GoMock package.
package route

import (
	dto "NotificationService/internal/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageSenderInterface is a mock of MessageSenderInterface interface.
type MockMessageSenderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderInterfaceMockRecorder
}

// MockMessageSenderInterfaceMockRecorder is the mock recorder for MockMessageSenderInterface.
type MockMessageSenderInterfaceMockRecorder struct {
	mock *MockMessageSenderInterface
}

// NewMockMessageSenderInterface creates a new mock instance.
func NewMockMessageSenderInterface(ctrl *gomock.Controller) *MockMessageSenderInterface {
	mock := &MockMessageSenderInterface{ctrl: ctrl}
	mock.recorder = &MockMessageSenderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSenderInterface) EXPECT() *MockMessageSenderInterfaceMockRecorder {
	return m.recorder
}

// HandleDistributions mocks base method.
func (m *MockMessageSenderInterface) HandleDistributions() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDistributions")
}

// HandleDistributions indicates an expected call of HandleDistributions.
func (mr *MockMessageSenderInterfaceMockRecorder) HandleDistributions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDistributions", reflect.TypeOf((*MockMessageSenderInterface)(nil).HandleDistributions))
}

// SendDistribution mocks base method.
func (m *MockMessageSenderInterface) SendDistribution(arg0 *dto.DistributionWithId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendDistribution", arg0)
}

// SendDistribution indicates an expected call of SendDistribution.
func (mr *MockMessageSenderInterfaceMockRecorder) SendDistribution(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDistribution", reflect.TypeOf((*MockMessageSenderInterface)(nil).SendDistribution), arg0)
}
